apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /home/wx/nfs_share/wordpress
    server: 192.168.31.59
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-db
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /home/wx/nfs_share/wordpress-db
    server: 192.168.31.59
