apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  hostPath:
    path: /home/ubuntu/k8s/learn/pv/pv-0003
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0004
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  mountOptions:
    - hard
    - nfsvers=4.1
  hostPath:
    path: /home/ubuntu/k8s/learn/pv/pv-0004
    type: Directory

