apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0001
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  nfs:
    path: /home/wx/nfs_share/pv-0001
    server: 192.168.31.59

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0002
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast
  nfs:
    path: /home/wx/nfs_share/pv-0002
    server: 192.168.31.59
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /home/wx/nfs_share/pv-0003
    server: 192.168.31.59

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0004
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /home/wx/nfs_share/pv-0004
    server: 192.168.31.59

