apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-0001
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: fast
